version: "3.8"
services:
  postgres:
    image: postgres:15
    ports:
      - "5435:5432"
    volumes:
      - type: bind
        source: ./db-attendance
        target: /var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres
    command:
      - "postgres"
      - "-c"
      - "track_commit_timestamp=on"
      - "-c"
      - "log_destination=stderr"

networks:
  postgres:
    driver: bridge
